[package]
name = "day_02"
version = "0.1.0"
authors = ["sbock <sebastian.bockholt@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.22"
